### ISSUE TITLE
Test applications in docker containers should run from a build on the host instead of starting their own build 

### ISSUE THREAD

**Issue by volkerstampa** [RBMHTechnology/eventuate-chaos#11]
Currently the docker container for the test application uses sbt to compile and run the build when the container starts. Instead of building the application in the container again the container should rather run the build result of a build on the host.

The [sbt-native-packager](https://github.com/sbt/sbt-native-packager) might be of help here as it allows to easily collect all required jars in one place and the application can be started without sbt.

**Comment by gabrielgiussi** [comment]
Hi @volkerstampa, I just want to ask you what downsides did you see about making the sbt build inside docker's build?
> uses sbt to compile and run the build when the container starts.

This sentence confuses me because AFAIK the build is not executed every time the container starts (i.e. `docker run ...`) but only when the image is builded (i.e. `docker build ...`)

I think the nice thing about doing project's build inside image's build is to avoid the need downloading sbt and all the libraries to someone who just wants to test the image with blockade and docker. Again, I'm new to docker so I'm trying to catch the good practices.

**Comment by volkerstampa** [comment]
@gabrielgiussi You are right, that building the container (`docker build ...`) does also build the application (`sbt ...`). However this is basically a preliminary build. When the container is started through blockade it runs the command found in the entrypoint (`sbt`) with the arguments in `blockade.yml` (`test:run-main com.rbmhtechnology.eventuate.chaos.ChaosActor -d`) and this will compile again, if source code, build file or dependencies have changed. The libraries are downloaded in any case. Currently within your container, with the other approach on your local machine. The eventuate-chaos project serves two main purposes. 

1. It demonstrates how one can use `docker` and `blockade` to chaos-test the own Eventuate-based application. So you can use it as a blueprint and setup something like that for your application. In that case the `ChaosActor` is basically replaced by the own application and you typically build that locally anyways. 
1. It is used to chaos-test Eventuate itself. However with the current setup it is pretty hard to get a local Eventuate build into the Docker container as the sbt running there does not have access to the local ivy repository.

Does that make sense?

**Comment by gabrielgiussi** [comment]
I'm still lost a little bit.
> this will compile again, if source code, build file or dependencies have changed

Isn't this what we want? If the code has changed the image build should build the project again, shouldn't?

>  with the current setup it is pretty hard to get a local Eventuate build into the Docker container as the sbt running there does not have access to the local ivy repository

I get that, otherwise we should do something like build base images with an specific eventuate version (currently in development probably). For example eventuate:v0.8-SNAPSHOT.
About sbt having no access to the local ivy repository, this isn't entirely true, is it? Could we mount the local ivy repository with VOLUME, like in [this gradle example](https://github.com/shekhargulati/52-technologies-in-2016/tree/master/39-docker#using-volume-to-share-gradle-repository-cache)?

**Comment by volkerstampa** [comment]
>> this will compile again, if source code, build file or dependencies have changed

> Isn't this what we want? If the code has changed the image build should build the project again, shouldn't?

Yes, but since `sbt` is also used when running the container, if you change the code and do not rebuild the container (`docker build ...`) the application will be built (compiled by `sbt`) when starting the container.

>About sbt having no access to the local ivy repository, this isn't entirely true, is it? Could we mount the local ivy repository with VOLUME, like in this gradle example?

It would indeed be possible to mount the local ivy-dir into the container. It does not seem to make the setup simpler, though. Additionally it comes with the disadvantage that if two containers are mounting the local ivy-dir their `sbt`s are getting into conflict making the startup much slower. An sbt based startup is anyways much slower than a pure jvm based one (what we get with the proposed approach).

**Comment by gabrielgiussi** [comment]
Great @volkerstampa , thanks for the very detailed responses.

**Comment by volkerstampa** [comment]
@gabrielgiussi You are welcome!
